version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    hostname: '127.0.0.1'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://www.gitlab.com:9090"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qq.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "xyz@qq.com"
        gitlab_rails['smtp_password'] = "xyz"
        gitlab_rails['smtp_domain'] = "qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'xyz@qq.com'
        gitlab_rails['gitlab_email_display_name'] = 'gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '9090:9090'
      - '2222:22'
    volumes:
      - '/usr/gitlab/config:/etc/gitlab'
      - '/usr/gitlab/logs:/var/log/gitlab'
      - '/usr/gitlab/data:/var/opt/gitlab'
